name: container.yml
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: 'node:24.13.0'

    steps:
      - uses: actions/checkout@v6
      - run: |
          node --version
          npm install              
