name: "matrices - exercice 1"
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        dotnet:
          - 5.0.17
          - 10.0.3
        buildMode:
          - Debug
          - Release
    runs-on: windows-latest

    steps:
       - name: Récupère le code source
         uses: actions/checkout@v6

       - name: Install .NET
         uses: actions/setup-dotnet@v5.1.0
         with:
           dotnet-version: ${{ matrix.dotnet }}

       - name: Restore dependencies
         run: dotnet restore

       - name: Build
         run: dotnet build --no-restore --configuration ${{ env.buildMode }}
         env:
           buildMode: ${{ matrix.buildMode }}

