name: "matrices - exercice 3"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2 # maximum 2 in //
      matrix:
        server:
          - prod1
          - prod2
          - prod3
          - prod4
          - prod5
          - prod6
          - prod7
          - prod8

    steps:
       - name: Deploy application
         run: echo "Deploy on ${{ matrix.server }}"
